Bug Fix: handle non existent data field in paginated data (#1359)
* Bug Fix: handle non existent data in page

The new list user saved searches returns no data field in the page if there is none.

A logged in user will get this error in the console:

```
TypeError: a.data is not iterable (cannot read property undefined)
```

This solves that

* remove console assertion